config/routes.rb
LibraryManager::Application.routes.draw do

  resources :books, :only => :index do
    resources :loans, :only => [:index, :new, :create] do
      member do
        put :replace
      end
    end
  end

  resources :students, :only => [:index, :show]
  
  devise_for :employees, :skip => :registrations

  root :to => 'books#index'
end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :title, :author

  has_many :loans

  validates :title, :presence => true
  validates :author, :presence => true

  def self.search_by_title_and_author(params)
    self.where("title ilike ? and author ilike ?", "%#{params[:title]}%", "%#{params[:author]}%")
  end

  def available?
    self.loans.pending.empty?
  end
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  devise :database_authenticatable, :rememberable, :validatable

  attr_accessible :full_name, :registration, :email, :password, :password_confirmation, :remember_me

  has_many :loans 
end

app/models/loan.rb
# encoding: UTF-8
class Loan < ActiveRecord::Base
  attr_accessible :returned, :employee_id, :student_id, :book_id, :end_at

  belongs_to :book
  belongs_to :student
  belongs_to :employee

  scope :pending, where(:returned => false)

  validates :end_at, :presence => true
  validates :student_id, :presence => true
  validates :book_id, :presence => true
  validate :end_date_must_be_valid, :if => lambda {|loan| loan.end_at.present?}
  validate :student_cant_borrow_with_pending_loans, :if => lambda {|loan| !loan.returned_changed? && loan.student.present?}

  delegate :full_name, :to => :student
  delegate :title, :to => :book

  def replace!
    self.returned_at = Time.now
    self.returned = true
    self.save
  end

  private

  def end_date_must_be_valid
    errors.add(:end_at, I18n.t('loan.must_be_a_date_after_today')) if self.end_at < Time.now
    errors.add(:end_at, I18n.t('loan.must_be_inferior_to_seven_days')) if self.end_at - Time.now > 7.days
  end

  def student_cant_borrow_with_pending_loans
    errors.add(:student_id, I18n.t('loan.student_cant_borrow_with_pending_loans')) if self.student.has_pending_loans?
  end
end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :full_name, :registration

  has_many :loans

  def self.search_by_full_name_and_registration(params)
    self.where("full_name ilike ? and registration ilike ?", "%#{params[:full_name]}%", "%#{params[:registration]}%")
  end

  def has_pending_loans?
    self.loans.pending.count > 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authenticate_employee!

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = if params[:search].present?
      Book.search_by_title_and_author(params[:search])
    else
      Book.all
    end
  end

end

app/controllers/loans_controller.rb
# encoding: utf-8

class LoansController < ApplicationController

  def index
    @book = Book.find(params[:book_id])
    @loans = @book.loans
  end

  def new
    @book = Book.find(params[:book_id])
    if @book.available?
      @loan = @book.loans.new(:employee_id => current_employee.id)
    else
      redirect_to books_path, :alert => I18n.t('loan.book_unavailable')
    end
  end

  def create
    @loan = Loan.new(params[:loan])
    if @loan.save
      redirect_to books_path, :notice => I18n.t('loan.succesfully_created')
    else
      @book = Book.find(params[:book_id])
      render :new
    end
  end

  def replace
    @loan = Loan.find(params[:id])
    @loan.replace!
    redirect_to books_path, :notice => I18n.t('loan.succesfully_replaced')
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  respond_to :html, :json
  
  def index
    params[:search] = {:full_name => params[:term]} if params[:term].present?
    @students = if params[:search].present?
      Student.search_by_full_name_and_registration(params[:search])
    else
      Student.all
    end
    respond_with @students
  end

  def show
    @student = Student.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def error_messages(model)
    flash_messages = []
    model.errors.full_messages.each do |message|
      text = content_tag(:div,
                         content_tag(:button, raw("&times;"), :class => "close", "data-dismiss" => "alert") +
                         message.html_safe, :class => "alert fade in alert-error")
      flash_messages << text if message
    end
    flash_messages.join("\n").html_safe
  end

  def format_time(time)
    time.strftime('%d/%m/%Y') if time.present?
  end

end

app/helpers/bootstrap_flash_helper.rb
module BootstrapFlashHelper
  ALERT_TYPES = [:error, :info, :success, :warning]

  def bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?
      
      type = :success if type == :notice
      type = :error   if type == :alert
      next unless ALERT_TYPES.include?(type)

      Array(message).each do |msg|
        text = content_tag(:div,
                           content_tag(:button, raw("&times;"), :class => "close", "data-dismiss" => "alert") +
                           msg.html_safe, :class => "alert fade in alert-#{type}")
        flash_messages << text if message
      end
    end
    flash_messages.join("\n").html_safe
  end
end

app/views/books/_book.html.erb
<tr>
  <td>
    <%= book.id %>
  </td>
  <td>
    <%= book.title %>
  </td>
  <td>
    <%= book.author %>
  </td>
  <td>
    <%= book.available? ? t('book.available') : t('book.unavailable') %>
  </td>
  <td>
    <% if book.available? %>
      <%= link_to t('loan.create') , new_book_loan_path(book), :class => 'btn btn-success' %>
    <% else %>
      <%= link_to t('loan.replace') , replace_book_loan_path(book, book.loans.last), :class => 'btn btn-danger', :method => :put %>
    <% end %>
    <%= link_to t('loan.index') , book_loans_path(book), :class => 'btn' %>
  </td>
</tr>

app/views/books/index.html.erb
<%= form_tag books_path, :method => :get do %>
  <fieldset>
    <legend><%= t('book.search') %></legend>
    <label><%= t('book.title') %></label>
    <%= text_field_tag 'search[title]', params[:search].try(:[], :title) %>
    <label><%= t('book.author') %></label>
    <%= text_field_tag 'search[author]', params[:search].try(:[], :author) %>
    <br />
    <%= submit_tag t('shared.search'), :class => 'btn' %>
  </fieldset>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th><%= t('book.title') %></th>
      <th><%= t('book.author') %></th>
      <th><%= t('book.situation') %></th>
      <th><%= t('shared.actions') %></th>
    </tr>
  </thead>
  <tbody>
    <%= render @books %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8">
    <title><%= content_for?(:title) ? yield(:title) : t('shared.title') %></title>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->
    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>
  <body>

    <div id="wrap">

      <div id="header" class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <div class="row">
              <div class="pull-left">
                <span class="brand"><%= t('shared.title') %></span>
              </div>
              <ul class="nav pull-right">
                <% if employee_signed_in? %>
                  <li class="divider-vertical"></li>
                  <li><%= link_to t('book.plural'), books_path %></li>
                  <li class="divider-vertical"></li>
                  <li><%= link_to t('student.plural'), students_path %></li>
                  <li class="divider-vertical"></li>
                  <li><%= link_to t('shared.log_out'), destroy_employee_session_path, :method => :delete %></li>
                  <li class="divider-vertical"></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>

      <div id="main-region" class="container">
        <div class="row">
            <div class="span12">
              <%= bootstrap_flash %>
              <%= yield :errors %>
              <%= yield %>
            </div>
          </div>
      </div>
      <div id="push"></div>

    </div>

    <div id="footer">
      <div class="container">
        <p class="muted">
          <%= "#{t('shared.title')} - #{t('shared.developed_by')} " %>
          <%= link_to 'Diego Felipe de Medeiros', 'http://github.com/dfmedeiros' %>
        </p>
      </div> 
    </div>

    
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/loans/_loan.html.erb
<tr>
  <td>
    <%= loan.id %>
  </td>
  <td>
    <%= loan.full_name %>
  </td>
  <td>
    <%= loan.title %>
  </td>
  <td>
    <%= format_time loan.created_at %>
  </td>
  <td>
    <%= format_time loan.end_at %>
  </td>
  <td>
    <%= format_time loan.returned_at %>
  </td>
  <td>
    <%= loan.returned? ? t('loan.returned') : t('loan.not_returned') %>
  </td>
  <td>
    <% unless loan.returned? %>
      <%= link_to t('loan.replace'), replace_book_loan_path(loan.book, loan), :class => 'btn btn-danger', :method => :put %>
    <% end %>
  </td>
</tr>

app/views/loans/index.html.erb
<div class="page-header">
  <h2><%= @book.title %></h2>
  <i><%= @book.author %></i>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th><%= t('student.single') %></th>
      <th><%= t('book.single') %></th>
      <th><%= t('loan.created_at') %></th>
      <th><%= t('loan.end_at') %></th>
      <th><%= t('loan.returned_at') %></th>
      <th><%= t('book.situation') %></th>
      <th><%= t('shared.actions') %></th>
    </tr>
  </thead>
  <tbody>
    <%= render @loans %>
  </tbody>
</table>

app/views/loans/new.html.erb
<%= content_for :errors do %>
  <%= error_messages @loan %> 
<% end %>

<%= form_for @loan, :url => book_loans_path(@book) do |f| %>
  <fieldset>
    <legend><%= t('loan.create') %> - <%= @book.title %></legend>
    <label><%= t('student.single') %></label>
    <%= f.select :student_id, options_from_collection_for_select(Student.all, :id, :full_name, params[:loan].try(:[], :student_id)), :include_blank => t('shared.select') %>
    <%= f.hidden_field :book_id, :value => @book.id %>
    <%= f.hidden_field :employee_id, :value => current_employee.id %>
    <label><%= t('loan.end_at') %></label>
    <%= f.text_field :end_at %>
    <br />
    <%= f.submit t('shared.save'), :class => 'btn' %>
  </fieldset>
<% end %>

app/views/students/_student.html.erb
<tr>
  <td>
    <%= student.id %>
  </td>
  <td>
    <%= student.registration %>
  </td>
  <td>
    <%= student.full_name %>
  </td>
  <td>
    <%= link_to t('student.see_details'), student_path(student), :class => 'btn' %>
  </td>
</tr>

app/views/students/index.html.erb
<%= form_tag students_path, :method => :get do %>
  <fieldset>
    <legend><%= t('student.search')%></legend>
    <label><%= t('student.full_name') %></label>
    <%= text_field_tag 'search[full_name]', params[:search] ? params[:search][:full_name] : '' %>
    <label><%= t('student.registration') %></label>
    <%= text_field_tag 'search[registration]', params[:search] ? params[:search][:registration] : '' %>
    <br />
    <%= submit_tag t('shared.search'), :class => 'btn' %>
  </fieldset>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th><%= t('student.registration') %></th>
      <th><%= t('student.full_name') %></th>
      <th><%= t('shared.actions') %></th>
    </tr>
  </thead>
  <tbody>
    <%= render @students %>
  </tbody>
</table>

app/views/students/show.html.erb
<div class="page-header">
  <h2><%= @student.full_name %></h2>
  <i><%= @student.registration %></i>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th><%= t('student.single') %></th>
      <th><%= t('book.single') %></th>
      <th><%= t('loan.created_at') %></th>
      <th><%= t('loan.end_at') %></th>
      <th><%= t('loan.returned_at') %></th>
      <th><%= t('book.situation') %></th>
      <th><%= t('shared.actions') %></th>
    </tr>
  </thead>
  <tbody>
    <%= render @student.loans %>
  </tbody>
</table>